version: 0.1
phases:
  install:
    commands:
      - 'touch .npmignore'
      - 'npm install -g gatsby'
  pre_build:
    commands:
      - 'npm install'
  build:
    commands:
      - 'npm run build'
      - 'aws s3 sync --delete "public/" "s3://www.carlosaherrera.com"'
  post_build:
    commands:
      - echo "POST BUILD STEP"
artifacts:
  base-directory: public
  files:
    - '**/*'
  discard-paths: yes