version: 0.2
phases:
  install:
    commands:
      - "touch .npmignore"
      - "npm install -g gatsby"
  pre_build:
    commands:
      - "cd wsite"
      - "npm install"
  build:
    commands:
      - "ls -la"
      - "npm run build"
  post_build:
    commands:
      - 'aws s3 sync --delete "./wsite/public/" "s3://www.carlosaherrera.com"'
artifacts:
  base-directory: public
  files:
    - "**/*"
  discard-paths: yes
